# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='pic_file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
