# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20170605_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='comment',
            field=models.CharField(default=None, max_length=100000),
        ),
        migrations.AlterField(
            model_name='notes',
            name='pic_file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
