# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20170609_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='info_group',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
