# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20180524_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='comment',
            field=models.CharField(blank=True, default=' ', max_length=100000, null=True),
        ),
    ]
