# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-07-26 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_auto_20180524_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Random_things',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_text', models.CharField(max_length=100000)),
                ('pic_file', models.FileField(blank=True, null=True, upload_to='')),
                ('hhh', models.CharField(default='1018', max_length=4)),
            ],
        ),
    ]
