# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-07-26 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_random_things'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Random_things',
            new_name='Randomnotes',
        ),
    ]
