# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2018-10-10 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_auto_20180726_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='lang',
            field=models.CharField(default='N', max_length=100),
        ),
    ]
