# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cook_ing', models.CharField(max_length=20)),
                ('cook_name', models.CharField(max_length=20)),
                ('cook_cat', models.CharField(max_length=50)),
                ('info_text', models.CharField(max_length=100000)),
                ('pic_file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
