# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='tag',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
