# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='comment',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
