# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
