# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20170716_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='cook_ing',
            field=models.CharField(max_length=50),
        ),
    ]
