# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20170716_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=10)),
                ('food_type', models.CharField(max_length=10)),
                ('quant', models.CharField(blank=True, max_length=10, null=True)),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
    ]
