# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=10)),
                ('ing', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
