# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_planner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('info_text', models.CharField(max_length=500)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
