# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_sweet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sweet',
        ),
    ]
