# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20170906_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='inputdate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
