# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_storage_inputdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='inputdate',
        ),
        migrations.AddField(
            model_name='storage',
            name='expire_flag',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
