# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_auto_20170909_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='expire_flag',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
