# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_food_hhh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel', models.FileField(upload_to='')),
                ('hhh', models.CharField(default='1018', max_length=4)),
            ],
        ),
    ]
